name: Build APK

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk libffi-dev libssl-dev zlib1g-dev git
          pip install --upgrade pip
          pip install buildozer cython

      - name: Create buildozer.spec
        run: |
          buildozer init
          sed -i 's/title = .*/title = Flag Game/' buildozer.spec
          sed -i 's/package.name = .*/package.name = flaggame/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.test/' buildozer.spec
          sed -i 's/requirements = .*/requirements = python3,kivy,requests/' buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
